import { MigrationInterface, QueryRunner } from "typeorm";

export class All1735942346484 implements MigrationInterface {
    name = 'All1735942346484'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_9bfd4060e7f71a77c6b82b1745b"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP CONSTRAINT "FK_c7bb556e83eddfd004f57b33229"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP CONSTRAINT "FK_76dc2a925952542bc16de2142b5"`);
        await queryRunner.query(`CREATE TABLE "company" ("id" SERIAL NOT NULL, "businessRegistrationNumber" character varying NOT NULL, "companyName" character varying NOT NULL, "businessOwner" character varying NOT NULL, "address" character varying NOT NULL, "addressDetail" character varying NOT NULL, "managerName" character varying NOT NULL, "managerEmail" character varying NOT NULL, "managerNumber" character varying NOT NULL, "employer_id" uuid, CONSTRAINT "REL_0301efca2c4d6ccc7ba4db5a39" UNIQUE ("employer_id"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('NONE', 'MAIL', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL DEFAULT '', "gender" "public"."user_gender_enum" NOT NULL DEFAULT 'NONE', "dateOfBirth" TIMESTAMP(0) WITH TIME ZONE, "profileImage" character varying NOT NULL DEFAULT '', "email" character varying(255) NOT NULL DEFAULT '', "isEmailVerified" boolean NOT NULL DEFAULT false, "emailVerificationCode" character varying(255), "phone" character varying(11) NOT NULL DEFAULT '', "isOverseasPhone" boolean NOT NULL DEFAULT false, "phoneVerificationCode" character varying(255), "address" character varying(255) NOT NULL DEFAULT '', "addressDetail" character varying(255) NOT NULL DEFAULT '', "isOverseasResident" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "applicant_id" uuid, CONSTRAINT "REL_52b0e8ed3202f5cdc36f7da279" UNIQUE ("applicant_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."license_licensestage_enum" AS ENUM('FIRST', 'SECOND', 'WRITTEN', 'PRACTICAL', 'FINAL')`);
        await queryRunner.query(`CREATE TABLE "license" ("id" SERIAL NOT NULL, "licenseName" character varying(100) NOT NULL, "licenseStage" "public"."license_licensestage_enum" NOT NULL, "dateOfCompletion" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "resume_id" integer, CONSTRAINT "UQ_1e64eb934ad65e514b1b24189f7" UNIQUE ("resume_id", "licenseName"), CONSTRAINT "PK_f168ac1ca5ba87286d03b2ef905" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."condition_job_enum" AS ENUM('MAINTENANCE', 'SECURITY', 'MANAGEMENT', 'MARKETING', 'IT_SUPPORT', 'ADMIN_SUPPORT', 'FACILITY_CLEANER', 'PARKING_ATTENDANT', 'OTHER', 'CLEANING', 'CLEANING_TEAM', 'BEDDING', 'CASHIER', 'DUTY_OFFICER', 'DUTY_ASSISTANT', 'CHEF', 'KITCHEN_ASSISTANT', 'MANAGER', 'GENERAL_MANAGER', 'ROOM_MANAGER', 'BANQUET_MANAGER', 'FOOD_BEVERAGE_MANAGER', 'OTHER_MANAGER', 'HOUSEKEEPING', 'ROOM_ATTENDANT', 'FRONT_DESK', 'CONCIERGE', 'VALET_PARKING', 'BELLBOY', 'EVENT_COORDINATOR', 'SPA_THERAPIST', 'SPA_MANAGER', 'FITNESS_TRAINER', 'RESTAURANT_MANAGER', 'BARTENDER', 'HEAD_CHEF', 'TOUR_COORDINATOR', 'CASINO_DEALER', 'GIFT_SHOP_ATTENDANT', 'POOL_ATTENDANT', 'KIDS_CLUB_STAFF')`);
        await queryRunner.query(`CREATE TYPE "public"."condition_employmenttype_enum" AS ENUM('FULL_TIME', 'CONTRACT', 'PART_TIME', 'DAILY_WORKER', 'INTERN')`);
        await queryRunner.query(`CREATE TYPE "public"."condition_salarytype_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`CREATE TYPE "public"."condition_benefit_enum" AS ENUM('HEALTH_INSURANCE', 'MEAL_SUPPORT', 'TRANSPORTATION_SUPPORT', 'HOUSING_SUPPORT', 'BONUS', 'PAID_LEAVE', 'FLEXIBLE_WORK', 'CHILDCARE_SUPPORT', 'RETIREMENT_PLAN')`);
        await queryRunner.query(`CREATE TABLE "condition" ("id" SERIAL NOT NULL, "job" "public"."condition_job_enum" NOT NULL, "employmentType" "public"."condition_employmenttype_enum" NOT NULL, "salaryType" "public"."condition_salarytype_enum" NOT NULL, "baseSalary" integer NOT NULL DEFAULT '0', "allowance" integer NOT NULL DEFAULT '0', "totalSalary" integer NOT NULL DEFAULT '0', "benefit" "public"."condition_benefit_enum" array NOT NULL DEFAULT '{}', "location" json NOT NULL DEFAULT '[]', "resume_id" integer, CONSTRAINT "REL_59de1c6c53acb130853172e589" UNIQUE ("resume_id"), CONSTRAINT "PK_f0f824897e3acf880a6e488b632" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."military_militarystatus_enum" AS ENUM('NONE', 'NOT_APPLICABLE', 'COMPLETED', 'NOT_COMPLETED', 'EXEMPTED', 'MEDICALLY_DISCHARGED')`);
        await queryRunner.query(`CREATE TABLE "military" ("id" SERIAL NOT NULL, "militaryStatus" "public"."military_militarystatus_enum" NOT NULL, "reason" character varying(255) NOT NULL DEFAULT '', "enlistmentDate" TIMESTAMP(0) WITH TIME ZONE, "dischargeDate" TIMESTAMP(0) WITH TIME ZONE, "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "resume_id" integer, CONSTRAINT "REL_2100c9bfbfb9ba5abd37afa682" UNIQUE ("resume_id"), CONSTRAINT "PK_8cec15e30cb876f84c78d58fbc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "salaryAmount"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "resumeId"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "marketingAgree"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "applicantId"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "languageSkills"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "careerDetails"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "responsibility" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "baseSalary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "resume_id" integer`);
        await queryRunner.query(`CREATE TYPE "public"."employer_accountstatus_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DELETED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "accountStatus" "public"."employer_accountstatus_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`CREATE TYPE "public"."employer_companyverificationstatus_enum" AS ENUM('NOT_REQUESTED', 'PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "companyVerificationStatus" "public"."employer_companyverificationstatus_enum" NOT NULL DEFAULT 'NOT_REQUESTED'`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "nickname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employer" ADD CONSTRAINT "UQ_089d8e683bd7db21b45abc92509" UNIQUE ("nickname")`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "passwordChangedAt" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "ageAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "smsMarketingAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "emailMarketingAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "employer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "consent" ADD CONSTRAINT "UQ_001277a5e6265d6fcc6d6dd2ef8" UNIQUE ("employer_id")`);
        await queryRunner.query(`CREATE TYPE "public"."resume_careerlevel_enum" AS ENUM('NEWBIE', 'EXPERIENCED')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "careerLevel" "public"."resume_careerlevel_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."resume_resumetype_enum" AS ENUM('FILE', 'GENERAL')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "resumeType" "public"."resume_resumetype_enum" NOT NULL DEFAULT 'GENERAL'`);
        await queryRunner.query(`CREATE TYPE "public"."resume_education_enum" AS ENUM('ELEMENTARY', 'MIDDLE_SCHOOL', 'HIGH_SCHOOL', 'COLLEGE_2_3_YEAR', 'COLLEGE_4_YEAR', 'MASTER', 'DOCTORATE')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "education" "public"."resume_education_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isGraduated" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "languages" json NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "careerDetail" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isRequiredAgreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isOptionalAgreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "applicant_id" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."experience_position_enum" RENAME TO "experience_position_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."experience_position_enum" AS ENUM('NONE', 'INTERN', 'PART_TIME', 'STAFF', 'ASSISTANT_MANAGER', 'MANAGER', 'TEAM_LEADER', 'DIRECTOR', 'GENERAL_MANAGER', 'EXECUTIVE', 'CEO')`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" TYPE "public"."experience_position_enum" USING "position"::"text"::"public"."experience_position_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."experience_position_enum_old"`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" SET DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "location"`);
        await queryRunner.query(`CREATE TYPE "public"."experience_location_enum" AS ENUM('NONE', '전국', '서울특별시', '부산광역시', '강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '세종특별자치시', '울산광역시', '인천광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도', '충청북도')`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "location" "public"."experience_location_enum" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TYPE "public"."experience_salarytype_enum" RENAME TO "experience_salarytype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."experience_salarytype_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" TYPE "public"."experience_salarytype_enum" USING "salaryType"::"text"::"public"."experience_salarytype_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."experience_salarytype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" SET DEFAULT 'SUBMITTED'`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "introduction" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_0301efca2c4d6ccc7ba4db5a393" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent" ADD CONSTRAINT "FK_001277a5e6265d6fcc6d6dd2ef8" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent" ADD CONSTRAINT "FK_c7bb556e83eddfd004f57b33229" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_52b0e8ed3202f5cdc36f7da2791" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license" ADD CONSTRAINT "FK_a78bf47cb7c48e5fba9aeb83f17" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "condition" ADD CONSTRAINT "FK_59de1c6c53acb130853172e589a" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resume" ADD CONSTRAINT "FK_5b19ae7262b795819b4d8dd1d30" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "military" ADD CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "military" DROP CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP CONSTRAINT "FK_5b19ae7262b795819b4d8dd1d30"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP CONSTRAINT "FK_59de1c6c53acb130853172e589a"`);
        await queryRunner.query(`ALTER TABLE "license" DROP CONSTRAINT "FK_a78bf47cb7c48e5fba9aeb83f17"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_52b0e8ed3202f5cdc36f7da2791"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP CONSTRAINT "FK_c7bb556e83eddfd004f57b33229"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP CONSTRAINT "FK_001277a5e6265d6fcc6d6dd2ef8"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_0301efca2c4d6ccc7ba4db5a393"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "introduction" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`CREATE TYPE "public"."experience_salarytype_enum_old" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY')`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" TYPE "public"."experience_salarytype_enum_old" USING "salaryType"::"text"::"public"."experience_salarytype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "salaryType" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."experience_salarytype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."experience_salarytype_enum_old" RENAME TO "experience_salarytype_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "location"`);
        await queryRunner.query(`DROP TYPE "public"."experience_location_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "location" character varying(255) DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."experience_position_enum_old" AS ENUM('INTERN', 'PART_TIME', 'STAFF', 'ASSISTANT_MANAGER', 'MANAGER', 'TEAM_LEADER', 'DIRECTOR', 'GENERAL_MANAGER', 'EXECUTIVE', 'CEO')`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "experience" ALTER COLUMN "position" TYPE "public"."experience_position_enum_old" USING "position"::"text"::"public"."experience_position_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."experience_position_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."experience_position_enum_old" RENAME TO "experience_position_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "applicant_id"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isOptionalAgreement"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isRequiredAgreement"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "careerDetail"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "languages"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isGraduated"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "education"`);
        await queryRunner.query(`DROP TYPE "public"."resume_education_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "resumeType"`);
        await queryRunner.query(`DROP TYPE "public"."resume_resumetype_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "careerLevel"`);
        await queryRunner.query(`DROP TYPE "public"."resume_careerlevel_enum"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP CONSTRAINT "UQ_001277a5e6265d6fcc6d6dd2ef8"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "employer_id"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "emailMarketingAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "smsMarketingAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "ageAgree"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "passwordChangedAt"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP CONSTRAINT "UQ_089d8e683bd7db21b45abc92509"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "companyVerificationStatus"`);
        await queryRunner.query(`DROP TYPE "public"."employer_companyverificationstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "accountStatus"`);
        await queryRunner.query(`DROP TYPE "public"."employer_accountstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "baseSalary"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "responsibility"`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "careerDetails" text DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "languageSkills" json DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "applicantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "marketingAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "resumeId" integer`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "salaryAmount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE "military"`);
        await queryRunner.query(`DROP TYPE "public"."military_militarystatus_enum"`);
        await queryRunner.query(`DROP TABLE "condition"`);
        await queryRunner.query(`DROP TYPE "public"."condition_benefit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."condition_salarytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."condition_employmenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."condition_job_enum"`);
        await queryRunner.query(`DROP TABLE "license"`);
        await queryRunner.query(`DROP TYPE "public"."license_licensestage_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`ALTER TABLE "resume" ADD CONSTRAINT "FK_76dc2a925952542bc16de2142b5" FOREIGN KEY ("applicantId") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent" ADD CONSTRAINT "FK_c7bb556e83eddfd004f57b33229" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_9bfd4060e7f71a77c6b82b1745b" FOREIGN KEY ("resumeId") REFERENCES "resume"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
