import { MigrationInterface, QueryRunner } from "typeorm";

export class SnakeConfig1735985420243 implements MigrationInterface {
    name = 'SnakeConfig1735985420243'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "license" DROP CONSTRAINT "UQ_1e64eb934ad65e514b1b24189f7"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "businessRegistrationNumber"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "companyName"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "businessOwner"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "addressDetail"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "managerName"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "managerEmail"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "managerNumber"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "accountStatus"`);
        await queryRunner.query(`DROP TYPE "public"."employer_accountstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "companyVerificationStatus"`);
        await queryRunner.query(`DROP TYPE "public"."employer_companyverificationstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "passwordChangedAt"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "personalInfoAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "serviceTermsAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "ageAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "smsMarketingAgree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "emailMarketingAgree"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "isEmployed"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "companyName"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "reasonForLeaving"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "salaryType"`);
        await queryRunner.query(`DROP TYPE "public"."experience_salarytype_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "totalSalary"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "baseSalary"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "licenseName"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "licenseStage"`);
        await queryRunner.query(`DROP TYPE "public"."license_licensestage_enum"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "dateOfCompletion"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "militaryStatus"`);
        await queryRunner.query(`DROP TYPE "public"."military_militarystatus_enum"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "enlistmentDate"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "dischargeDate"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "employmentType"`);
        await queryRunner.query(`DROP TYPE "public"."condition_employmenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "salaryType"`);
        await queryRunner.query(`DROP TYPE "public"."condition_salarytype_enum"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "baseSalary"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "totalSalary"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isVisible"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isDefault"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "sanctionReason"`);
        await queryRunner.query(`DROP TYPE "public"."resume_sanctionreason_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "careerLevel"`);
        await queryRunner.query(`DROP TYPE "public"."resume_careerlevel_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "resumeType"`);
        await queryRunner.query(`DROP TYPE "public"."resume_resumetype_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isGraduated"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "careerDetail"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isRequiredAgreement"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "isOptionalAgreement"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "UQ_546a819aa07c196d7aa0f9d17db"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "dateOfBirth"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "profileImage"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isEmailVerified"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "emailVerificationCode"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isOverseasPhone"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phoneVerificationCode"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "addressDetail"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isOverseasResident"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "business_registration_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "company_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "business_owner" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "address_detail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "manager_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "manager_email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "manager_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."employer_account_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DELETED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "account_status" "public"."employer_account_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`CREATE TYPE "public"."employer_company_verification_status_enum" AS ENUM('NOT_REQUESTED', 'PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "company_verification_status" "public"."employer_company_verification_status_enum" NOT NULL DEFAULT 'NOT_REQUESTED'`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "password_changed_at" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "age_agree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "personal_info_agree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "service_terms_agree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "sms_marketing_agree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "email_marketing_agree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "company_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "is_employed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "start_date" TIMESTAMP(0) WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "end_date" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "reason_for_leaving" character varying(255) DEFAULT ''`);
        await queryRunner.query(`CREATE TYPE "public"."experience_salary_type_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "salary_type" "public"."experience_salary_type_enum" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "base_salary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "total_salary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "license" ADD "license_name" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."license_license_stage_enum" AS ENUM('FIRST', 'SECOND', 'WRITTEN', 'PRACTICAL', 'FINAL')`);
        await queryRunner.query(`ALTER TABLE "license" ADD "license_stage" "public"."license_license_stage_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "license" ADD "date_of_completion" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "license" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "license" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."military_military_status_enum" AS ENUM('NONE', 'NOT_APPLICABLE', 'COMPLETED', 'NOT_COMPLETED', 'EXEMPTED', 'MEDICALLY_DISCHARGED')`);
        await queryRunner.query(`ALTER TABLE "military" ADD "military_status" "public"."military_military_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "military" ADD "enlistment_date" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "military" ADD "discharge_date" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "military" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "military" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."condition_employment_type_enum" AS ENUM('FULL_TIME', 'CONTRACT', 'PART_TIME', 'DAILY_WORKER', 'INTERN')`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "employment_type" "public"."condition_employment_type_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."condition_salary_type_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "salary_type" "public"."condition_salary_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "base_salary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "total_salary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_visible" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_default" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."resume_sanction_reason_enum" AS ENUM('NONE', 'INAPPROPRIATE_LANGUAGE', 'FALSE_INFORMATION', 'ILLEGAL_CONTENT', 'POLICY_VIOLATION')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "sanction_reason" "public"."resume_sanction_reason_enum" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`CREATE TYPE "public"."resume_career_level_enum" AS ENUM('NEWBIE', 'EXPERIENCED')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "career_level" "public"."resume_career_level_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."resume_resume_type_enum" AS ENUM('FILE', 'GENERAL')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "resume_type" "public"."resume_resume_type_enum" NOT NULL DEFAULT 'GENERAL'`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_graduated" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "career_detail" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_required_agreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_optional_agreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "UQ_1c33583f19967b0e56ee23bafce" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "date_of_birth" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ADD "profile_image" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "user" ADD "is_email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "email_verification_code" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD "is_overseas_phone" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phone_verification_code" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD "address_detail" character varying(255) NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "user" ADD "is_overseas_resident" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "license" ADD CONSTRAINT "UQ_16591ed2ce33a008f78016ebd31" UNIQUE ("resume_id", "license_name")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "license" DROP CONSTRAINT "UQ_16591ed2ce33a008f78016ebd31"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "is_overseas_resident"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "address_detail"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phone_verification_code"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "is_overseas_phone"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "email_verification_code"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "is_email_verified"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "profile_image"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "UQ_1c33583f19967b0e56ee23bafce"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_optional_agreement"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_required_agreement"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "career_detail"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_graduated"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "resume_type"`);
        await queryRunner.query(`DROP TYPE "public"."resume_resume_type_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "career_level"`);
        await queryRunner.query(`DROP TYPE "public"."resume_career_level_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "sanction_reason"`);
        await queryRunner.query(`DROP TYPE "public"."resume_sanction_reason_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_default"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_visible"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "total_salary"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "base_salary"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "salary_type"`);
        await queryRunner.query(`DROP TYPE "public"."condition_salary_type_enum"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "employment_type"`);
        await queryRunner.query(`DROP TYPE "public"."condition_employment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "discharge_date"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "enlistment_date"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "military_status"`);
        await queryRunner.query(`DROP TYPE "public"."military_military_status_enum"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "date_of_completion"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "license_stage"`);
        await queryRunner.query(`DROP TYPE "public"."license_license_stage_enum"`);
        await queryRunner.query(`ALTER TABLE "license" DROP COLUMN "license_name"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "total_salary"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "base_salary"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "salary_type"`);
        await queryRunner.query(`DROP TYPE "public"."experience_salary_type_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "reason_for_leaving"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "is_employed"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "email_marketing_agree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "sms_marketing_agree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "service_terms_agree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "personal_info_agree"`);
        await queryRunner.query(`ALTER TABLE "consent" DROP COLUMN "age_agree"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "password_changed_at"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "company_verification_status"`);
        await queryRunner.query(`DROP TYPE "public"."employer_company_verification_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "account_status"`);
        await queryRunner.query(`DROP TYPE "public"."employer_account_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "manager_number"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "manager_email"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "manager_name"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "address_detail"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "business_owner"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "business_registration_number"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "isOverseasResident" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "addressDetail" character varying(255) NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phoneVerificationCode" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD "isOverseasPhone" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "emailVerificationCode" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD "isEmailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "profileImage" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "user" ADD "dateOfBirth" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "UQ_546a819aa07c196d7aa0f9d17db" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isOptionalAgreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isRequiredAgreement" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "careerDetail" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isGraduated" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`CREATE TYPE "public"."resume_resumetype_enum" AS ENUM('FILE', 'GENERAL')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "resumeType" "public"."resume_resumetype_enum" NOT NULL DEFAULT 'GENERAL'`);
        await queryRunner.query(`CREATE TYPE "public"."resume_careerlevel_enum" AS ENUM('NEWBIE', 'EXPERIENCED')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "careerLevel" "public"."resume_careerlevel_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."resume_sanctionreason_enum" AS ENUM('NONE', 'INAPPROPRIATE_LANGUAGE', 'FALSE_INFORMATION', 'ILLEGAL_CONTENT', 'POLICY_VIOLATION')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "sanctionReason" "public"."resume_sanctionreason_enum" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isDefault" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "isVisible" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "totalSalary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "baseSalary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."condition_salarytype_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "salaryType" "public"."condition_salarytype_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."condition_employmenttype_enum" AS ENUM('FULL_TIME', 'CONTRACT', 'PART_TIME', 'DAILY_WORKER', 'INTERN')`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "employmentType" "public"."condition_employmenttype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "military" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "military" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "military" ADD "dischargeDate" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "military" ADD "enlistmentDate" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."military_militarystatus_enum" AS ENUM('NONE', 'NOT_APPLICABLE', 'COMPLETED', 'NOT_COMPLETED', 'EXEMPTED', 'MEDICALLY_DISCHARGED')`);
        await queryRunner.query(`ALTER TABLE "military" ADD "militaryStatus" "public"."military_militarystatus_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "license" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "license" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "license" ADD "dateOfCompletion" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."license_licensestage_enum" AS ENUM('FIRST', 'SECOND', 'WRITTEN', 'PRACTICAL', 'FINAL')`);
        await queryRunner.query(`ALTER TABLE "license" ADD "licenseStage" "public"."license_licensestage_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "license" ADD "licenseName" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "baseSalary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "totalSalary" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."experience_salarytype_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "salaryType" "public"."experience_salarytype_enum" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "reasonForLeaving" character varying(255) DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "endDate" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "startDate" TIMESTAMP(0) WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "companyName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "isEmployed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "emailMarketingAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "smsMarketingAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "ageAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "serviceTermsAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "consent" ADD "personalInfoAgree" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "passwordChangedAt" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."employer_companyverificationstatus_enum" AS ENUM('NOT_REQUESTED', 'PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "companyVerificationStatus" "public"."employer_companyverificationstatus_enum" NOT NULL DEFAULT 'NOT_REQUESTED'`);
        await queryRunner.query(`CREATE TYPE "public"."employer_accountstatus_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DELETED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "accountStatus" "public"."employer_accountstatus_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "managerNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "managerEmail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "managerName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "addressDetail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "businessOwner" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "companyName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD "businessRegistrationNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "license" ADD CONSTRAINT "UQ_1e64eb934ad65e514b1b24189f7" UNIQUE ("licenseName", "resume_id")`);
    }

}
