import { MigrationInterface, QueryRunner } from "typeorm";

export class ApplicationTable1737370895009 implements MigrationInterface {
    name = 'ApplicationTable1737370895009'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_resume_uuid"`);
        await queryRunner.query(`CREATE TABLE "recruitment_nationality" ("id" SERIAL NOT NULL, "korean" boolean NOT NULL DEFAULT false, "foreigner" boolean NOT NULL DEFAULT false, "marriage_visa" character varying(30), "recruitment_id" uuid, CONSTRAINT "REL_2d644548716c83f37669af13ff" UNIQUE ("recruitment_id"), CONSTRAINT "PK_e8a9161533b01b6e305ea2eb7b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "failure_reason" character varying, "payment_method" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_recruitment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid, "recruit_id" uuid, CONSTRAINT "PK_aea8ab06988ab4465548804fcfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."application_application_status_enum" AS ENUM('APPLIED', 'CANCELED')`);
        await queryRunner.query(`CREATE TYPE "public"."application_review_stage_status_enum" AS ENUM('DOCUMENT', 'INTERVIEW', 'ACCEPT', 'REJECT')`);
        await queryRunner.query(`CREATE TYPE "public"."application_employer_review_stage_status_enum" AS ENUM('DOCUMENT', 'INTERVIEW', 'ACCEPT', 'REJECT')`);
        await queryRunner.query(`CREATE TABLE "application" ("id" SERIAL NOT NULL, "resume_snapshot" jsonb, "application_status" "public"."application_application_status_enum" NOT NULL, "review_stage_status" "public"."application_review_stage_status_enum" NOT NULL DEFAULT 'DOCUMENT', "employer_review_stage_status" "public"."application_employer_review_stage_status_enum" NOT NULL DEFAULT 'DOCUMENT', "is_view" boolean NOT NULL DEFAULT false, "view_at" TIMESTAMP(0) WITH TIME ZONE, "apply_at" TIMESTAMP(0) WITH TIME ZONE, "cancel_at" TIMESTAMP(0) WITH TIME ZONE, "accept_at" TIMESTAMP(0) WITH TIME ZONE, "reject_at" TIMESTAMP(0) WITH TIME ZONE, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "resume_id" uuid, "recruitment_id" uuid, CONSTRAINT "PK_569e0c3e863ebdf5f2408ee1670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_recruitment_status_enum" AS ENUM('PROGRESS', 'PUBLISHED', 'CLOSED', 'REVIEWING', 'DRAFT')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_jobs_enum" AS ENUM('MAINTENANCE', 'SECURITY', 'MANAGEMENT', 'MARKETING', 'IT_SUPPORT', 'ADMIN_SUPPORT', 'FACILITY_CLEANER', 'PARKING_ATTENDANT', 'OTHER', 'CLEANING', 'CLEANING_TEAM', 'BEDDING', 'CASHIER', 'DUTY_OFFICER', 'DUTY_ASSISTANT', 'CHEF', 'KITCHEN_ASSISTANT', 'MANAGER', 'GENERAL_MANAGER', 'ROOM_MANAGER', 'BANQUET_MANAGER', 'FOOD_BEVERAGE_MANAGER', 'OTHER_MANAGER', 'HOUSEKEEPING', 'ROOM_ATTENDANT', 'FRONT_DESK', 'CONCIERGE', 'VALET_PARKING', 'BELLBOY', 'EVENT_COORDINATOR', 'SPA_THERAPIST', 'SPA_MANAGER', 'FITNESS_TRAINER', 'RESTAURANT_MANAGER', 'BARTENDER', 'HEAD_CHEF', 'TOUR_COORDINATOR', 'CASINO_DEALER', 'GIFT_SHOP_ATTENDANT', 'POOL_ATTENDANT', 'KIDS_CLUB_STAFF')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_experience_condition_enum" AS ENUM('NOT_REQUIRED', 'EXPERIENCED', 'NEWBIE')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_education_condition_enum" AS ENUM('NOT_REQUIRED', 'ELEMENTARY', 'MIDDLE_SCHOOL', 'HIGH_SCHOOL', 'COLLEGE_2_3_YEAR', 'COLLEGE_4_YEAR', 'MASTER', 'DOCTORATE')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_position_enum" AS ENUM('NONE', 'INTERN', 'PART_TIME', 'STAFF', 'ASSISTANT_MANAGER', 'MANAGER', 'TEAM_LEADER', 'DIRECTOR', 'GENERAL_MANAGER', 'EXECUTIVE', 'CEO')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_preferences_enum" AS ENUM('LICENSE_HOTEL_ADMINISTRATOR', 'LICENSE_FOOD_SANITATION_MANAGER', 'LICENSE_TOURISM_INTERPRETER_GUIDE', 'LICENSE_BARISTA', 'LICENSE_GUEST_SERVICE_MANAGER', 'LICENSE_FIRST_AID', 'LICENSE_SECURITY_GUARD', 'LICENSE_HOUSEKEEPING_CERTIFICATE', 'LICENSE_FOOD_AND_BEVERAGE_MANAGER', 'LICENSE_CUSTOMER_SERVICE_CERTIFICATE', 'LANGUAGE_KOREAN', 'LANGUAGE_ENGLISH', 'LANGUAGE_SPANISH', 'LANGUAGE_CHINESE', 'LANGUAGE_JAPANESE', 'LANGUAGE_FRENCH', 'LANGUAGE_RUSSIAN', 'LANGUAGE_MONGOLIAN', 'NEAR_RESIDENT', 'VEHICLE_OWNER', 'NIGHT_SHIFT', 'TWO_SHIFT', 'THREE_SHIFT', 'DRIVER', 'DORMITORY_LIFE', 'REGIONAL_WORK', 'ALTERNATE_SHIFT', 'GPA_ABOVE_4', 'COMPUTER_SKILLS_EXCELLENT', 'EXCEL_ADVANCED', 'PPT_SKILLS_EXCELLENT', 'STATISTICAL_ANALYSIS_EXPERT', 'DOCUMENT_WRITING_EXCELLENT', 'ACCOUNTING_EXPERT', 'PHOTOSHOP_EXPERT', 'SAFETY_MANAGER_CERTIFICATE', 'BOILER_ENGINEER_CERTIFICATE', 'ELECTRICIAN_CERTIFICATE', 'PLUMBING_TECHNICIAN_CERTIFICATE', 'FIRE_SAFETY_MANAGER', 'AIR_CONDITIONING_ENGINEER', 'ENVIRONMENTAL_ENGINEER', 'ENERGY_MANAGER_CERTIFICATE', 'BUILDING_MAINTENANCE_CERTIFICATE')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_salary_type_enum" AS ENUM('NONE', 'ANNUAL', 'MONTHLY', 'DAILY', 'HOURLY')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_working_day_enum" AS ENUM('WEEKDAYS_5', 'WEEKDAYS_6', 'WEEKEND_DAY', 'WEEKEND_NIGHT', 'NIGHT', 'TO_BE_DECIDED', 'TWO_SHIFT_DAY_DAY_NIGHT_NIGHT', 'TWO_SHIFT_DAY_NIGHT_OFF_OFF', 'TWO_SHIFT_DAY_NIGHT', 'THREE_SHIFT_DAY_DAY_NIGHT_NIGHT_OFF_OFF', 'THREE_SHIFT_DAY_NIGHT_OFF', 'THREE_SHIFT_MORNING_AFTERNOON_NIGHT', 'ALTERNATE_DAY_SHIFT', 'ALTERNATE_NIGHT_SHIFT', 'ALTERNATE_2DAY_OFF')`);
        await queryRunner.query(`CREATE TYPE "public"."recruitment_benefits_enum" AS ENUM('SALARY_RETIREMENT_PENSION', 'SALARY_INCENTIVE', 'SALARY_BONUS', 'SALARY_LONG_TERM_RECOGNITION', 'SALARY_PERFORMANCE_BONUS', 'SALARY_SEVERANCE_PAY', 'SALARY_EMPLOYEE_AWARD', 'SALARY_NIGHT_ALLOWANCE', 'SALARY_HOLIDAY_ALLOWANCE', 'SALARY_ANNUAL_ALLOWANCE', 'SALARY_POSITION_ALLOWANCE', 'SALARY_CERTIFICATION_ALLOWANCE', 'SALARY_LONG_TERM_ALLOWANCE', 'SALARY_RISK_ALLOWANCE', 'SALARY_SOCIAL_INSURANCE', 'CULTURE_FLAT_ORGANIZATION', 'CULTURE_NO_COMPULSORY_MEALS', 'CULTURE_NIGHT_SHIFT_OPT_OUT', 'CULTURE_FREE_DRESS_CODE', 'CULTURE_CULTURAL_MEETINGS', 'CULTURE_GUARANTEED_RETIREMENT', 'GIFTS_HOLIDAY_GIFT_OR_EXPENSES', 'GIFTS_FOUNDATION_GIFT', 'GIFTS_BIRTHDAY_GIFT_PARTY', 'GIFTS_CHRISTMAS_GIFT', 'GIFTS_WEDDING_GIFT', 'GIFTS_MATERNITY_GIFT', 'GIFTS_BIRTHDAY_EARLY_LEAVE', 'GIFTS_LONG_SERVICE_GIFT', 'WORK_LIFE_DORMITORY_OPERATION', 'WORK_LIFE_VEHICLE_FUEL_SUPPORT', 'WORK_LIFE_COMMUTER_BUS', 'WORK_LIFE_HOUSING_PROVISION', 'WORK_LIFE_HOUSING_LOAN', 'WORK_LIFE_NIGHT_COMMUTE_ALLOWANCE', 'WORK_LIFE_COMPANY_VEHICLE', 'WORK_LIFE_PARKING_SUPPORT', 'WORK_LIFE_RENT_SUPPORT', 'WORK_LIFE_HOUSING_ALLOWANCE', 'WORK_LIFE_COMMUTE_SUPPORT', 'SUPPORT_HEALTH_HEALTH_CHECKUP', 'SUPPORT_HEALTH_MEDICAL_SUPPORT_SELF', 'SUPPORT_HEALTH_MEDICAL_SUPPORT_FAMILY', 'SUPPORT_HEALTH_SMOKING_CESSATION', 'SUPPORT_HEALTH_EMPLOYEE_LOAN', 'SUPPORT_HEALTH_GROUP_INSURANCE', 'SUPPORT_HEALTH_FITNESS_CENTER', 'SUPPORT_HEALTH_WEDDING_PREPARATION', 'SUPPORT_HEALTH_DISCOUNT_PRODUCTS', 'SUPPORT_HEALTH_CULTURAL_ACTIVITY', 'SUPPORT_HEALTH_COMMUNICATION_SUPPORT', 'SUPPORT_HEALTH_WELFARE_CARD_POINTS', 'SUPPORT_HEALTH_INTERNAL_WEDDING_HALL', 'SUPPORT_HEALTH_SCHOLARSHIP_CHILDREN', 'SUPPORT_HEALTH_SUBSIDY_FOR_SURVEY', 'SUPPORT_HEALTH_HEALTH_SUBSIDY', 'SUPPORT_HEALTH_FREE_MEDICAL', 'SUPPORT_HEALTH_SELECTIVE_WELFARE', 'SUPPORT_HEALTH_INTERNAL_RECRUITMENT', 'REFRESH_ANNUAL_LEAVE', 'REFRESH_SUMMER_LEAVE', 'REFRESH_FAMILY_EVENT_LEAVE', 'REFRESH_HALF_DAY_LEAVE', 'REFRESH_REFRESH_LEAVE', 'REFRESH_FOUNDATION_DAY_LEAVE', 'REFRESH_LABOR_DAY_LEAVE', 'REFRESH_LEAVE_ALLOWANCE', 'REFRESH_AWARD_LEAVE', 'REFRESH_MATERNITY_LEAVE', 'REFRESH_PARENTAL_LEAVE', 'REFRESH_PATERNITY_LEAVE', 'REFRESH_SICK_LEAVE', 'REFRESH_HOLIDAY_FACILITY', 'REFRESH_FAMILY_DAY', 'REFRESH_TIME_OFF_EXTENSION', 'REFRESH_PUBLIC_HOLIDAY_LEAVE')`);
        await queryRunner.query(`CREATE TABLE "recruitment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recruitment_title" character varying NOT NULL, "recruitment_status" "public"."recruitment_recruitment_status_enum" NOT NULL, "jobs" "public"."recruitment_jobs_enum" array, "experience_condition" "public"."recruitment_experience_condition_enum", "education_condition" "public"."recruitment_education_condition_enum" NOT NULL DEFAULT 'NOT_REQUIRED', "recruitment_capacity" integer NOT NULL, "department" character varying NOT NULL DEFAULT '', "position" "public"."recruitment_position_enum", "preferences" "public"."recruitment_preferences_enum" array NOT NULL DEFAULT '{}', "content" text NOT NULL, "employment_type" jsonb NOT NULL DEFAULT '{"FULL_TIME":false,"CONTRACT":false,"DAILY_WORKER":false,"PART_TIME":false,"INTERN":false}', "salary_type" "public"."recruitment_salary_type_enum" NOT NULL DEFAULT 'MONTHLY', "salary_amount" integer NOT NULL DEFAULT '0', "working_day" "public"."recruitment_working_day_enum", "working_time" jsonb NOT NULL DEFAULT '{"start":"","end":""}', "benefits" "public"."recruitment_benefits_enum" array NOT NULL DEFAULT '{}', "hotel_name" character varying NOT NULL DEFAULT '', "room_count" integer NOT NULL DEFAULT '0', "address" character varying NOT NULL DEFAULT '', "address_detail" character varying NOT NULL DEFAULT '', "manager_name" character varying NOT NULL DEFAULT '', "is_name_private" boolean NOT NULL DEFAULT false, "manager_number" character varying NOT NULL DEFAULT '', "is_number_private" boolean NOT NULL DEFAULT false, "manager_email" character varying NOT NULL DEFAULT '', "is_email_private" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "employer_id" uuid, CONSTRAINT "PK_fb4ef13a6aadbf704c92679b09a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."account_history_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DEACTIVATED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`CREATE TABLE "account_history" ("id" SERIAL NOT NULL, "user_id" character varying NOT NULL, "status" "public"."account_history_status_enum" NOT NULL, "changed_by" character varying, "changed_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "note" text, "applicant_id" uuid, "employer_id" uuid, CONSTRAINT "PK_de0652296aa9d641c6269104b98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_resume_view" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_652a2a9c05dcc092865282f696a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_jump" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_09376fab115471ae767c09f9366" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "resume" DROP CONSTRAINT "UQ_19b4c58aadb0dcba0c453f43ec6"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "is_graduated"`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "profile_image" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."resume_local_code_enum" AS ENUM('01', '02')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "local_code" "public"."resume_local_code_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."resume_sex_code_enum" AS ENUM('01', '02')`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "sex_code" "public"."resume_sex_code_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "email" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "birthday" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "address" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "address_detail" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "licenses" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "resume_id" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."employer_account_status_enum" RENAME TO "employer_account_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employer_account_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DEACTIVATED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" TYPE "public"."employer_account_status_enum" USING "account_status"::"text"::"public"."employer_account_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employer_account_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."applicant_account_status_enum" RENAME TO "applicant_account_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."applicant_account_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DEACTIVATED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" TYPE "public"."applicant_account_status_enum" USING "account_status"::"text"::"public"."applicant_account_status_enum"`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."applicant_account_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "nickname" SET DEFAULT '5968088496'`);
        await queryRunner.query(`ALTER TABLE "military" DROP CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829"`);
        await queryRunner.query(`ALTER TABLE "military" DROP CONSTRAINT "REL_2100c9bfbfb9ba5abd37afa682"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "military" ADD "resume_id" uuid`);
        await queryRunner.query(`ALTER TABLE "military" ADD CONSTRAINT "UQ_2100c9bfbfb9ba5abd37afa6829" UNIQUE ("resume_id")`);
        await queryRunner.query(`ALTER TABLE "condition" DROP CONSTRAINT "FK_59de1c6c53acb130853172e589a"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP CONSTRAINT "REL_59de1c6c53acb130853172e589"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "resume_id" uuid`);
        await queryRunner.query(`ALTER TABLE "condition" ADD CONSTRAINT "UQ_59de1c6c53acb130853172e589a" UNIQUE ("resume_id")`);
        await queryRunner.query(`ALTER TABLE "resume" DROP CONSTRAINT "PK_7ff05ea7599e13fac01ac812e48"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "resume" ADD CONSTRAINT "PK_7ff05ea7599e13fac01ac812e48" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TYPE "public"."resume_status_enum" RENAME TO "resume_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."resume_status_enum" AS ENUM('DRAFT', 'PUBLISH', 'HIDDEN', 'ERROR')`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" TYPE "public"."resume_status_enum" USING "status"::"text"::"public"."resume_status_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."resume_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "career_level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "education" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recruitment_nationality" ADD CONSTRAINT "FK_2d644548716c83f37669af13ff4" FOREIGN KEY ("recruitment_id") REFERENCES "recruitment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD CONSTRAINT "FK_4b39415deeac15ffdcc1843689e" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD CONSTRAINT "FK_2d629dbdbed075f082566becfc2" FOREIGN KEY ("recruit_id") REFERENCES "recruitment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_935b116e508b76c0a2fa730bc2c" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_f9dde63d2e371d5bb29a5281fcd" FOREIGN KEY ("recruitment_id") REFERENCES "recruitment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recruitment" ADD CONSTRAINT "FK_1833487288f0fcbe84c29a6aee7" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_history" ADD CONSTRAINT "FK_a23b19a227b14d6b648b393a02a" FOREIGN KEY ("applicant_id") REFERENCES "applicant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_history" ADD CONSTRAINT "FK_961e266e81510443fad71ac7247" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "military" ADD CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "condition" ADD CONSTRAINT "FK_59de1c6c53acb130853172e589a" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "condition" DROP CONSTRAINT "FK_59de1c6c53acb130853172e589a"`);
        await queryRunner.query(`ALTER TABLE "military" DROP CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829"`);
        await queryRunner.query(`ALTER TABLE "account_history" DROP CONSTRAINT "FK_961e266e81510443fad71ac7247"`);
        await queryRunner.query(`ALTER TABLE "account_history" DROP CONSTRAINT "FK_a23b19a227b14d6b648b393a02a"`);
        await queryRunner.query(`ALTER TABLE "recruitment" DROP CONSTRAINT "FK_1833487288f0fcbe84c29a6aee7"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_f9dde63d2e371d5bb29a5281fcd"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_935b116e508b76c0a2fa730bc2c"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP CONSTRAINT "FK_2d629dbdbed075f082566becfc2"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP CONSTRAINT "FK_4b39415deeac15ffdcc1843689e"`);
        await queryRunner.query(`ALTER TABLE "recruitment_nationality" DROP CONSTRAINT "FK_2d644548716c83f37669af13ff4"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "education" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "career_level" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."resume_status_enum_old" AS ENUM('DRAFT', 'SUBMITTED', 'HIDDEN', 'DELETED')`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" TYPE "public"."resume_status_enum_old" USING "status"::"text"::"public"."resume_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "resume" ALTER COLUMN "status" SET DEFAULT 'SUBMITTED'`);
        await queryRunner.query(`DROP TYPE "public"."resume_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."resume_status_enum_old" RENAME TO "resume_status_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP CONSTRAINT "PK_7ff05ea7599e13fac01ac812e48"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resume" ADD CONSTRAINT "PK_7ff05ea7599e13fac01ac812e48" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "condition" DROP CONSTRAINT "UQ_59de1c6c53acb130853172e589a"`);
        await queryRunner.query(`ALTER TABLE "condition" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "condition" ADD "resume_id" integer`);
        await queryRunner.query(`ALTER TABLE "condition" ADD CONSTRAINT "REL_59de1c6c53acb130853172e589" UNIQUE ("resume_id")`);
        await queryRunner.query(`ALTER TABLE "condition" ADD CONSTRAINT "FK_59de1c6c53acb130853172e589a" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "military" DROP CONSTRAINT "UQ_2100c9bfbfb9ba5abd37afa6829"`);
        await queryRunner.query(`ALTER TABLE "military" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "military" ADD "resume_id" integer`);
        await queryRunner.query(`ALTER TABLE "military" ADD CONSTRAINT "REL_2100c9bfbfb9ba5abd37afa682" UNIQUE ("resume_id")`);
        await queryRunner.query(`ALTER TABLE "military" ADD CONSTRAINT "FK_2100c9bfbfb9ba5abd37afa6829" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "nickname" SET DEFAULT '3463077247'`);
        await queryRunner.query(`CREATE TYPE "public"."applicant_account_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DELETED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" TYPE "public"."applicant_account_status_enum_old" USING "account_status"::"text"::"public"."applicant_account_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "account_status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."applicant_account_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."applicant_account_status_enum_old" RENAME TO "applicant_account_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."employer_account_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'SUSPENDED', 'LOCKED', 'DELETED', 'PENDING', 'RECOVERY', 'ANONYMIZED', 'WAITING_APPROVAL')`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" TYPE "public"."employer_account_status_enum_old" USING "account_status"::"text"::"public"."employer_account_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employer" ALTER COLUMN "account_status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employer_account_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employer_account_status_enum_old" RENAME TO "employer_account_status_enum"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP COLUMN "resume_id"`);
        await queryRunner.query(`ALTER TABLE "experience" ADD "resume_id" integer`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_6b65e2a85c9838ca97137e4ef5b" FOREIGN KEY ("resume_id") REFERENCES "resume"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "licenses"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "address_detail"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "birthday"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "sex_code"`);
        await queryRunner.query(`DROP TYPE "public"."resume_sex_code_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "local_code"`);
        await queryRunner.query(`DROP TYPE "public"."resume_local_code_enum"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "resume" DROP COLUMN "profile_image"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "is_graduated" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "resume" ADD "uuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "resume" ADD CONSTRAINT "UQ_19b4c58aadb0dcba0c453f43ec6" UNIQUE ("uuid")`);
        await queryRunner.query(`DROP TABLE "payment_jump"`);
        await queryRunner.query(`DROP TABLE "payment_resume_view"`);
        await queryRunner.query(`DROP TABLE "account_history"`);
        await queryRunner.query(`DROP TYPE "public"."account_history_status_enum"`);
        await queryRunner.query(`DROP TABLE "recruitment"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_benefits_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_working_day_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_salary_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_preferences_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_position_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_education_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_experience_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_jobs_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recruitment_recruitment_status_enum"`);
        await queryRunner.query(`DROP TABLE "application"`);
        await queryRunner.query(`DROP TYPE "public"."application_employer_review_stage_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."application_review_stage_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."application_application_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment_recruitment"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "recruitment_nationality"`);
        await queryRunner.query(`CREATE INDEX "idx_resume_uuid" ON "resume" ("uuid") `);
    }

}
