import { MigrationInterface, QueryRunner } from "typeorm";

export class DevcreateMem1738981794566 implements MigrationInterface {
    name = 'DevcreateMem1738981794566'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP CONSTRAINT "FK_2d629dbdbed075f082566becfc2"`);
        await queryRunner.query(`CREATE TYPE "public"."push_provider_enum" AS ENUM('LOCAL', 'KAKAO', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "push" ("id" SERIAL NOT NULL, "user_uuid" character varying NOT NULL, "provider" "public"."push_provider_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "token" character varying(255) NOT NULL, "device" character varying, "browser" character varying, "user_agent" character varying, "notification_settings" jsonb DEFAULT '{}', "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ddc3812b04a238cbf8606c12ea6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_discount_type_enum" AS ENUM('FIXED', 'PERCENTAGE')`);
        await queryRunner.query(`CREATE TABLE "coupon" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "discount_type" "public"."coupon_discount_type_enum" NOT NULL, "discount_rate" numeric(4,2) NOT NULL DEFAULT '0', "discount_amount" integer NOT NULL DEFAULT '0', "min_order_amount" integer NOT NULL DEFAULT '0', "max_discount_amount" integer NOT NULL DEFAULT '0', "is_single_use" boolean NOT NULL DEFAULT true, "is_public" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP(0) WITH TIME ZONE, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_62d3c5b0ce63a82c48e86d904bc" UNIQUE ("code"), CONSTRAINT "PK_fcbe9d72b60eed35f46dc35a682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employer_coupon" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_used" boolean NOT NULL DEFAULT false, "used_at" TIMESTAMP(0) WITH TIME ZONE, "expires_at" TIMESTAMP(0) WITH TIME ZONE, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "employer_id" uuid, "coupon_id" uuid, CONSTRAINT "PK_c8422cb0274bbc6c41c284335fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "m_id" character varying NOT NULL, "last_transaction_key" character varying NOT NULL, "payment_key" character varying NOT NULL, "order_id" character varying NOT NULL, "order_name" character varying NOT NULL, "status" character varying NOT NULL, "secret" character varying, "method" character varying NOT NULL, "type" character varying NOT NULL, "failure" jsonb, "is_partial_cancelable" boolean NOT NULL, "receipt" jsonb, "total_amount" integer NOT NULL, "balance_amount" integer NOT NULL, "supplied_amount" integer NOT NULL, "vat" numeric(10,2) NOT NULL, "issuer_code" character varying NOT NULL, "acquirer_code" character varying NOT NULL, "number" character varying NOT NULL, "installment_plan_months" integer NOT NULL, "is_interest_free" boolean NOT NULL, "interest_payer" character varying, "approve_no" character varying NOT NULL, "use_card_point" boolean NOT NULL, "card_type" character varying NOT NULL, "owner_type" character varying NOT NULL, "acquire_status" character varying NOT NULL, "amount" integer NOT NULL, "requested_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL, "approved_at" TIMESTAMP(0) WITH TIME ZONE, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "payment_id" uuid, CONSTRAINT "UQ_7d0c099f8df5dbcb573daacb41c" UNIQUE ("payment_key"), CONSTRAINT "PK_82c3470854cf4642dfb0d7150cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_options_name_enum" AS ENUM('LIST_UP', 'HIGHLIGHT', 'TAG', 'BOLD')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_options_duration_enum" AS ENUM('3', '5', '7', '10', '14', '21')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_options_tags_enum" AS ENUM('URGENT', 'POPULAR', 'RECOMMENDED', 'NEW')`);
        await queryRunner.query(`CREATE TABLE "payment_recruitment_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."payment_recruitment_options_name_enum" NOT NULL, "duration" "public"."payment_recruitment_options_duration_enum" NOT NULL, "max_list_up_per_day" integer NOT NULL DEFAULT '0', "list_up_interval_hours" integer NOT NULL DEFAULT '0', "tags" "public"."payment_recruitment_options_tags_enum" array NOT NULL DEFAULT '{}', "price" integer NOT NULL DEFAULT '0', "payment_recruitment_id" uuid, CONSTRAINT "PK_9a8283d27a15854a26dd775d3be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."point_transaction_type_enum" AS ENUM('EARN', 'USE', 'EXPIRE')`);
        await queryRunner.query(`CREATE TABLE "point_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."point_transaction_type_enum" NOT NULL, "point" integer NOT NULL, "description" character varying(255), "expiration_date" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "employer_id" uuid, "payment_id" uuid, CONSTRAINT "PK_b56b792bcf7f60a32758005caf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "score"`);
        await queryRunner.query(`ALTER TABLE "recruitment_product_option" ADD "price" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "order_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "UQ_f5221735ace059250daac9d9803" UNIQUE ("order_id")`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "applied_coupon_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "original_amount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "discount_amount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "total_amount" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_payment_status_enum" AS ENUM('PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'PAYMENT_EXPIRED', 'CANCEL_REQUESTED', 'CANCEL_COMPLETED', 'REFUND_REQUESTED', 'REFUND_COMPLETED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "payment_status" "public"."payment_payment_status_enum" NOT NULL DEFAULT 'PAYMENT_PENDING'`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "expires_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "employer_coupon_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_name_enum" AS ENUM('PREMIUM', 'SPECIAL', 'URGENT', 'BASIC')`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "name" "public"."payment_recruitment_name_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_type_enum" AS ENUM('RECRUIT', 'MAIN')`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "type" "public"."payment_recruitment_type_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_recruitment_duration_enum" AS ENUM('3', '5', '7', '10', '14', '21')`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "duration" "public"."payment_recruitment_duration_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "bonus_days" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "price" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD "discount_rate" numeric(4,3) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "application" ADD "recruitment_snapshot" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."application_final_decision_status_enum" AS ENUM('ACCEPT', 'REJECT', 'PENDING')`);
        await queryRunner.query(`ALTER TABLE "application" ADD "final_decision_status" "public"."application_final_decision_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "recruitment" ADD "posting_start_date" TIMESTAMP(0) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "recruitment" ADD "posting_end_date" TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "total_score" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "total_point" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "user_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "failure_reason"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "failure_reason" jsonb`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "membership" ALTER COLUMN "discount_rate" TYPE numeric(4,2)`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "nickname" SET DEFAULT '3931489523'`);
        await queryRunner.query(`CREATE INDEX "IDX_f5221735ace059250daac9d980" ON "payment" ("order_id") `);
        await queryRunner.query(`ALTER TABLE "employer_coupon" ADD CONSTRAINT "FK_0ffb5e24cb4682fd401db12c7dd" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employer_coupon" ADD CONSTRAINT "FK_49f538e2bb0fb7f1778d1e1fc25" FOREIGN KEY ("coupon_id") REFERENCES "coupon"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" ADD CONSTRAINT "FK_287282a4ba5518a1aac033d1fd7" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_d4283086c79d7ea732e9f138abd" FOREIGN KEY ("employer_coupon_id") REFERENCES "employer_coupon"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD CONSTRAINT "FK_2d629dbdbed075f082566becfc2" FOREIGN KEY ("recruit_id") REFERENCES "recruitment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment_options" ADD CONSTRAINT "FK_88aec36ecf2a9e203a5e831302b" FOREIGN KEY ("payment_recruitment_id") REFERENCES "payment_recruitment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transaction" ADD CONSTRAINT "FK_98f935ff104955d2ee525d1e725" FOREIGN KEY ("employer_id") REFERENCES "employer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transaction" ADD CONSTRAINT "FK_a8eb70fc3c225adf9b933423d78" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "point_transaction" DROP CONSTRAINT "FK_a8eb70fc3c225adf9b933423d78"`);
        await queryRunner.query(`ALTER TABLE "point_transaction" DROP CONSTRAINT "FK_98f935ff104955d2ee525d1e725"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment_options" DROP CONSTRAINT "FK_88aec36ecf2a9e203a5e831302b"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP CONSTRAINT "FK_2d629dbdbed075f082566becfc2"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_d4283086c79d7ea732e9f138abd"`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" DROP CONSTRAINT "FK_287282a4ba5518a1aac033d1fd7"`);
        await queryRunner.query(`ALTER TABLE "employer_coupon" DROP CONSTRAINT "FK_49f538e2bb0fb7f1778d1e1fc25"`);
        await queryRunner.query(`ALTER TABLE "employer_coupon" DROP CONSTRAINT "FK_0ffb5e24cb4682fd401db12c7dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5221735ace059250daac9d980"`);
        await queryRunner.query(`ALTER TABLE "applicant" ALTER COLUMN "nickname" SET DEFAULT '4423914498'`);
        await queryRunner.query(`ALTER TABLE "membership" ALTER COLUMN "discount_rate" TYPE numeric(4,3)`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "updated_at" TIMESTAMP(6) NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "created_at" TIMESTAMP(6) NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "failure_reason"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "failure_reason" character varying`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "total_point"`);
        await queryRunner.query(`ALTER TABLE "employer" DROP COLUMN "total_score"`);
        await queryRunner.query(`ALTER TABLE "recruitment" DROP COLUMN "posting_end_date"`);
        await queryRunner.query(`ALTER TABLE "recruitment" DROP COLUMN "posting_start_date"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "final_decision_status"`);
        await queryRunner.query(`DROP TYPE "public"."application_final_decision_status_enum"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "recruitment_snapshot"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "discount_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "bonus_days"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "duration"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_duration_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" DROP COLUMN "name"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_name_enum"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "employer_coupon_id"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "payment_status"`);
        await queryRunner.query(`DROP TYPE "public"."payment_payment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "total_amount"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "discount_amount"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "original_amount"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "applied_coupon_id"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "UQ_f5221735ace059250daac9d9803"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "recruitment_product_option" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "employer" ADD "score" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "status" character varying NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "amount" numeric(10,2) NOT NULL`);
        await queryRunner.query(`DROP TABLE "point_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."point_transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "payment_recruitment_options"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_options_tags_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_options_duration_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_recruitment_options_name_enum"`);
        await queryRunner.query(`DROP TABLE "payment_transaction"`);
        await queryRunner.query(`DROP TABLE "employer_coupon"`);
        await queryRunner.query(`DROP TABLE "coupon"`);
        await queryRunner.query(`DROP TYPE "public"."coupon_discount_type_enum"`);
        await queryRunner.query(`DROP TABLE "push"`);
        await queryRunner.query(`DROP TYPE "public"."push_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_recruitment" ADD CONSTRAINT "FK_2d629dbdbed075f082566becfc2" FOREIGN KEY ("recruit_id") REFERENCES "recruitment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
