version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: dev/hotel-job-api
    container_name: hotel-job-api-dev_c
    ports:
    - "8010:8010"