name: ECS Deployment

on:
  workflow_dispatch:
  push:
   
jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download ECS Task Definition 
        run: |
          aws ecs describe-task-definition \
          --task-definition hotel-job-api-prod-task \
          --region ${{ secrets.AWS_REGION }} \
          --output json > task-definition.json


